name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run configuration script
        run: ./config.sh --url https://github.com/sananabbasov/springboot-logistic-app --token AI2NREAQWLP2RZHHOCV2C6TGNXNZM
